#整合Mybatis
mybatis:
  #加载Mybatisd的全局配置文件
  #mapper-locations: classpath:SqlMapConfig.xml
  #加载Mybatisd的映射配置文件
  #mapper-locations: classpath:mapper/*Mapper.xml
  #别名定义
  type-aliases-package: com.itgaoshu.bean

#配置Druid连接池数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.196.241.234:3306/gscms
    driver-class-name: com.mysql.jdbc.Driver
    username: yqq
    password: Yqq123456

  #配置FreeMarker模板引擎
  freemarker:
    cache: false
    charset: UTF-8
    template-loader-path: classpath:/templates/
    suffix: .ftl
    content-type: text/html
 #配置redis
  redis:
  #指定IP地址:
  host: 127.0.0.1
  #指定redis端口号
  port: 6379